//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnioAcademico
    {
        public int AnioAcademicoID { get; set; }
        public Nullable<int> Anio { get; set; }
        public bool Activo { get; set; }
    }
}
