//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesorAsignatura
    {
        public int ProfesorAsignaturaID { get; set; }
        public int ProfesorID { get; set; }
        public int AsignaturaID { get; set; }
        public int AnioAcademicoID { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
