//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Client.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SincoERPEntities : DbContext
    {
        public SincoERPEntities()
            : base("name=SincoERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<AlumnoAsignatura> AlumnoAsignatura { get; set; }
        public virtual DbSet<AnioAcademico> AnioAcademico { get; set; }
        public virtual DbSet<Asignatura> Asignatura { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<ProfesorAsignatura> ProfesorAsignatura { get; set; }
        public virtual DbSet<Vista_AsignaturasProfesor> Vista_AsignaturasProfesor { get; set; }
        public virtual DbSet<Vista_CalificacionAlumno> Vista_CalificacionAlumno { get; set; }
    }
}
